-- AlterTable
ALTER TABLE "user" ALTER COLUMN "emailVerified" DROP NOT NULL,
ALTER COLUMN "emailVerified" SET DEFAULT false,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "role" SET DEFAULT 'user',
ALTER COLUMN "banned" SET DEFAULT false,
ALTER COLUMN "phone" DROP NOT NULL;
